### ISSUE TITLE
Segmentation vs Object detection?

### ISSUE THREAD

**Issue by aysark** [developmentseed/skynet-train#48]
Is there a reason why you guys chose to do semantic segmentation approach vs object detection?  Wouldn't it be easier to train and have better accuracy if you are just trying to label the object and not worried about correctness/completeness pixel metrics?

**Comment by drewbo** [comment]
@aysark our first use case for this was road identification which doesn't work quite as well with object detection (since the bounding box is less informative than a segmentation mask). We've since abstracted out some of the data prep work such that it can be applied to object-detection approaches as well https://github.com/developmentseed/label-maker. We'll be following up in the next few days with some additional documentation and tutorials on this new repo. Thanks!
